--[ 테이블 생성 / 더미데이터 입력 ]

-- [ 테이블 생성 ]

------------------- 1차 테이블 생성 -----------------------------------------------------------------------------------

--○ 관리자(ADMIN) 테이블 생성
CREATE TABLE ADMIN
( ID    VARCHAR2(20)    
, PW    VARCHAR2(20)    NOT NULL
,CONSTRAINT ADMIN_ID_PK PRIMARY KEY(ID)
);


--○ 교재(BOOKS) 테이블 생성
CREATE TABLE BOOKS
( NUM    NUMBER      
, NAME   VARCHAR2(30)       CONSTRAINT BOOKS_NAME_NN    NOT NULL
, CONSTRAINT BOOKS_NUM_PK   PRIMARY KEY(NUM) 
, CONSTRAINT BOOKS_NAME_UK UNIQUE(NAME)
);


--○ 학생(STUDENTS) 테이블 생성
CREATE TABLE STUDENTS
( ID    VARCHAR2(20)
, NAME  VARCHAR2(20)    CONSTRAINT STUDENTS_NAME_NN NOT NULL
, PW    VARCHAR2(20)    CONSTRAINT STUDENTS_PW_NN NOT NULL
, SSN   CHAR(7)         CONSTRAINT STUDENTS_SSN_NN NOT NULL
, CONSTRAINT STUDENTS_ID_PK PRIMARY KEY(ID)
);


--○ 과목명 테이블 생성
CREATE TABLE SUBJECTS
( CODE  NUMBER
, NAME  VARCHAR2(20) CONSTRAINT SUBJECTS_NAME_NN NOT NULL
, CONSTRAINT SUBJECTS_CODE_PK PRIMARY KEY(CODE)
, CONSTRAINT SUBJECTS_NAME_UK UNIQUE(NAME)
);


--○ 강의실명 테이블 생성
CREATE TABLE CLASSROOMS
( CODE  NUMBER
, INFO  VARCHAR2(50) CONSTRAINT CLASSROOMS_INFO_NN NOT NULL
, CONSTRAINT CLASSROOMS_CODE_PK PRIMARY KEY(CODE)
, CONSTRAINT CLASSROOMS_INFO_UK UNIQUE(INFO)
);

--○ 과정명 테이블 생성
CREATE TABLE COURSES
( CODE  NUMBER
, NAME  VARCHAR2(100) CONSTRAINT COURSES_NAME_NN NOT NULL
, CONSTRAINT COURSES_CODE_PK PRIMARY KEY(CODE)
, CONSTRAINT COURSES_NAME_UK UNIQUE(NAME)
);

--○ 교수자 테이블 생성 
CREATE TABLE PROFESSORS
( ID    VARCHAR2(20)
, PW    VARCHAR2(20)    CONSTRAINT PROFESSORS_PW_NN NOT NULL
, SSN   CHAR(7)         CONSTRAINT PROFESSORS_SSN_NN NOT NULL
, NAME  VARCHAR2(30)    CONSTRAINT PROFESSORS_NAME_NN NOT NULL
, CONSTRAINT PROFESSORS_ID_PK PRIMARY KEY(ID)
);


-------------------------2차 테이블 생성 --------------------------------------------------------------------------

--○ 개설과정(OP_COURSES) 테이블 생성
CREATE TABLE OP_COURSES
( CODE          NUMBER
, ROOM_CODE     NUMBER          CONSTRAINT OP_COURSES_ROOM_CODE_NN NOT NULL
, COURSE_CODE   NUMBER          CONSTRAINT OP_COURSES_COURSE_CODE_NN NOT NULL
, PRO_ID        VARCHAR2(10)    
, START_DATE    DATE            CONSTRAINT OP_COURSES_START_NN NOT NULL
, END_DATE      DATE            CONSTRAINT OP_COURSES_END_NN NOT NULL
, CONSTRAINT OP_COURSES_CODE_PK PRIMARY KEY(CODE)
, CONSTRAINT OP_COURSES_ROOM_CODE_FK FOREIGN KEY(ROOM_CODE)
             REFERENCES CLASSROOMS(CODE)
             ON DELETE CASCADE
, CONSTRAINT OP_COURSES_COURSE_CODE_FK FOREIGN KEY(COURSE_CODE)
             REFERENCES COURSES(CODE)
             ON DELETE CASCADE
, CONSTRAINT OP_COURSES_PRO_ID_FK FOREIGN KEY(PRO_ID)
             REFERENCES PROFESSORS(ID)
             ON DELETE CASCADE             
, CONSTRAINT OP_COURSES_UK UNIQUE (START_DATE, END_DATE, COURSE_CODE, PRO_ID)             
);
                  

--○ 교수자 강의 가능 과목 테이블 생성
CREATE TABLE PROFESSOR_TEACHABLE_SUBJECTS
( CODE      NUMBER    
, PRO_ID    VARCHAR2(20)    CONSTRAINT PTS_PRO_ID_NN NOT NULL
, SUB_CODE  NUMBER    CONSTRAINT PTS_SUB_CODE_NN NOT NULL
, CONSTRAINT PTS_CODE_PK PRIMARY KEY(CODE)
, CONSTRAINT PTS_PRO_ID_FK FOREIGN KEY(PRO_ID)
        REFERENCES PROFESSORS(ID)
        ON DELETE CASCADE
, CONSTRAINT PTS_SUB_CODE_FK FOREIGN KEY(SUB_CODE)
        REFERENCES SUBJECTS(CODE)
        ON DELETE CASCADE
, CONSTRAINT PTS_PRO_SUB_UK UNIQUE(PRO_ID, SUB_CODE)        
);


-----------------------3차 테이블 생성---------------------------------------------------------------------------------------

--○ 개설 과목(OP_SUBJECTS) 테이블 생성 
CREATE TABLE OP_SUBJECTS
( NUM               NUMBER
, BOOK_NUM          NUMBER       
, PTS_CODE          NUMBER       CONSTRAINT OP_SUBJECTS_PTS_COD_NN NOT NULL
, OP_COURSE_CODE    NUMBER       CONSTRAINT OP_SUBJECTS_OP_COURSE_CODE_NN NOT NULL
, START_DATE        DATE         CONSTRAINT OP_SUBJECTS_START_DATE_NN NOT NULL
, END_DATE          DATE         CONSTRAINT OP_SUBJECTS_END_DATE_NN   NOT NULL
, PRE_RATE          NUMBER(3)    
, PRAC_RATE         NUMBER(3)    
, WRITE_RATE        NUMBER(3)    
, CONSTRAINT OP_SUBJECTS_NUM_PK PRIMARY KEY(NUM)
, CONSTRAINT OP_SUBJECTS_BOOK_NUM_FK FOREIGN KEY(BOOK_NUM)
        REFERENCES BOOKS(NUM)
        
, CONSTRAINT OP_SUBJECTS_PTS_CODE_FK FOREIGN KEY(PTS_CODE)
        REFERENCES PROFESSOR_TEACHABLE_SUBJECTS(CODE)
        ON DELETE CASCADE
, CONSTRAINT OP_SUBJECTS_OP_COURSE_CODE_FK FOREIGN KEY(OP_COURSE_CODE)
        REFERENCES OP_COURSES(CODE)
        ON DELETE CASCADE
, CONSTRAINT OP_SUBJECTS_START_DATE_CK CHECK(START_DATE<END_DATE)
, CONSTRAINT OP_SUBJECTS_RATE_SUM_CK CHECK(PRE_RATE + PRAC_RATE + WRITE_RATE = 100 AND PRE_RATE>=0 AND PRAC_RATE>=0 AND WRITE_RATE>=0)
);


--○ 학생별 과정수강목록(STUDENTS_COURSES_LIST) 테이블 생성

CREATE TABLE STUDENT_COURSES_LISTS
( NUM NUMBER
, STUDENT_ID VARCHAR2(20)           CONSTRAINT SCL_STUDENT_ID_NN NOT NULL
, OP_COURSE_CODE NUMBER             CONSTRAINT SCL_OP_COURSE_CODE_NN NOT NULL    
,CONSTRAINT SCL_NUM_PK PRIMARY KEY(NUM)

,CONSTRAINT SCL_STUDENT_ID_FK FOREIGN KEY(STUDENT_ID) 
                          REFERENCES STUDENTS(ID)
                          ON DELETE CASCADE
,CONSTRAINT SCL_OP_COURSE_CODE_FK FOREIGN KEY(OP_COURSE_CODE)
                          REFERENCES OP_COURSES(CODE)
                          ON DELETE CASCADE
);


               
----------------------4차 테이블 생성 ------------------------------------------------------------------------------------------

--○ 성적(SCORES) 테이블 생성 --!! 수정해야함!!! 출결점수 NUMBER(3), 점수는 NULL 가능 
CREATE TABLE SCORES
( NUM           NUMBER  
, SCL_NUM       NUMBER      CONSTRAINT SCORES_SCL_NUM_NN    NOT NULL
, OP_SUB_NUM    NUMBER      CONSTRAINT SCORES_OP_SUB_NUM_NN NOT NULL
, PRESENCE      NUMBER(3)    
, PRACTICE      NUMBER(3)  
, WRITING       NUMBER(3)  
, CONSTRAINT SCORES_NUM_PK  PRIMARY KEY(NUM)

, CONSTRAINT SCL_NUM_FK     FOREIGN KEY(SCL_NUM)
        REFERENCES STUDENT_COURSES_LISTS(NUM)
        ON DELETE CASCADE
, CONSTRAINT OP_SUB_NUM_FK  FOREIGN KEY(OP_SUB_NUM)
        REFERENCES OP_SUBJECTS(NUM)
        ON DELETE CASCADE
, CONSTRAINT  SCORES_PRESENCE_CK CHECK(PRESENCE BETWEEN 0 AND 100)
, CONSTRAINT  SCORES_PRACTICE_CK CHECK(PRACTICE BETWEEN 0 AND 100)
, CONSTRAINT  SCORES_WRITING_CK CHECK(WRITING BETWEEN 0 AND 100)
);

                          

--○ 중도탈락여부(NON_PASS)
CREATE TABLE NON_PASS
( NUM       NUMBER
, SCL_NUM   NUMBER  CONSTRAINT NON_PASS_SCL_NUM_NN    NOT NULL
, NP_DATE   DATE    CONSTRAINT NON_PASS_NP_DATE_NN    NOT NULL
, CONSTRAINT NON_PASS_NUM_PK    PRIMARY KEY(NUM)
, CONSTRAINT NON_PASS_SCL_NUM_FK FOREIGN KEY(SCL_NUM)
            REFERENCES STUDENT_COURSES_LISTS(NUM)
            ON DELETE CASCADE
);


------------------ 테이블 생성 완료 -------------------------------------------------------------------------------------------

--○ 테이블 생성 확인
SELECT  *
FROM TAB;

--○ 제약조건 생성 확인
SELECT *
FROM USER_CONSTRAINTS;

--○ 시퀀스 생성
CREATE SEQUENCE SEQ_PROFESSORS_ID NOCACHE;
CREATE SEQUENCE SEQ_COURSES_CODE NOCACHE;
CREATE SEQUENCE SEQ_OP_COURSES_CODE NOCACHE;
CREATE SEQUENCE SEQ_OP_SUBJECTS_CODE NOCACHE;
CREATE SEQUENCE SEQ_PTS_CODE NOCACHE;
CREATE SEQUENCE SEQ_SUBJECTS NOCACHE;
CREATE SEQUENCE SEQ_STUDENT_ID NOCACHE;
CREATE SEQUENCE SEQ_SCL_NUM NOCACHE;
CREATE SEQUENCE SEQ_SCORES NOCACHE;
CREATE SEQUENCE SEQ_NON_PASS NOCACHE;
CREATE SEQUENCE SEQ_BOOKS NOCACHE;
CREATE SEQUENCE SEQ_CLASSROOMS NOCACHE;


-- [ 더미데이터 입력 ] 

------------------- 1차 더미데이터 입력 ---------------------------------------------------------------------------------------

--○ 관리자(ADMIN) 데이터 입력
INSERT INTO ADMIN(ID,PW) VALUES ('abc' , '123');
INSERT INTO ADMIN(ID, PW) VALUES ('team3', 'java006$');


--○ 교재(BOOKS) 데이터 입력
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'자바의 정석'); 
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'오라클의 정석');
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'HTML의 정석');
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'CSS의 정석');
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'자바스크립트의 정석'); 
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'JQUERY의 정석'); 
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'JSP의 정석'); 
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'C의 정석'); 
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'파이썬의 정석'); 
INSERT INTO BOOKS(NUM,NAME) VALUES (SEQ_BOOKS.NEXTVAL,'스프링의 정석'); 


--○ 학생(STUDENTS) 데이터 입력
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '김학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '이학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '박학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '최학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '강학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '장학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '신학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '차학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '오학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '공학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '임학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '유학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '성학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '민학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '고학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '노학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '소학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '나학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '안학생');
INSERT INTO STUDENTS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_STUDENT_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '문학생');


--○ 교수(PROFESSORS) 데이터 입력
INSERT INTO PROFESSORS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_PROFESSORS_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '김교수');
INSERT INTO PROFESSORS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_PROFESSORS_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '이교수');
INSERT INTO PROFESSORS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_PROFESSORS_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '박교수');
INSERT INTO PROFESSORS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_PROFESSORS_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '최교수');
INSERT INTO PROFESSORS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_PROFESSORS_ID.NEXTVAL, 6, '0'), '1234567', '1234567', '강교수');
INSERT INTO PROFESSORS(ID, PW, SSN, NAME) VALUES (LPAD(SEQ_PROFESSORS_ID.NEXTVAL, 6, '0'), '2234567', '2234567', '장교수');



--○ 과정명 데이터 입력
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, '자바 프론트엔드 개발자 양성과정');
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, 'C++ 기반 프로그래밍 구축 및 관리 개발자 양성');
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, '자바 웹 개발자 중급반');
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, '자바 웹개발 기초부터 상급 까지 교육');
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, '인공지능 개발자 전문과 과정');
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, '실무기반 AR/VR 핵심인력 육성과정');
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, 'Open Source Web application 전문 개발자 양성과정');
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, '자바 기반 크로스 플랫폼 웹콘텐츠 개발자 양성과정');
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, 'NCS기반의 정보처리기사 자격증 취득과정');
INSERT INTO COURSES(CODE, NAME) VALUES(SEQ_COURSES_CODE.NEXTVAL, '디지털컨버전스 기반 UIUX Front 전문 개발자 양성');


--○ 과목명 데이터 입력
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '자바 이론');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '자바 실습');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '오라클 이론');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '오라클 실습');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, 'JAVA SPRING 이론');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, 'JAVA SPRING 실습');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, 'HTML/CSS/JS 이론');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, 'HTML/CSS/JS 실습');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '파이썬 이론');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '파이썬 실습');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '빅데이터 이론');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '빅데이터 실습');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '앱 개발 이론');
INSERT INTO SUBJECTS(CODE, NAME) VALUES (SEQ_SUBJECTS.NEXTVAL, '앱 개발 실습');



--○ 강의실 데이터 입력 
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'A강의실');
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'B강의실');
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'C강의실');
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'D강의실');
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'E강의실');
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'F강의실');
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'G강의실');
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'H강의실');
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'I강의실');
INSERT INTO CLASSROOMS(CODE, INFO) VALUES(SEQ_CLASSROOMS.NEXTVAL, 'J강의실');


------------------- 2차 더미데이터 입력 ---------------------------------------------------------------------------------------

--○ 개설과정(OP_COURSES) 데이터 입력
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 1, 1, '000001', TO_DATE('2018-04-16', 'YYYY-MM-DD'), TO_DATE('2018-10-15', 'YYYY-MM-DD'));
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 2, 2, '000002', TO_DATE('2018-07-23', 'YYYY-MM-DD'), TO_DATE('2019-01-11', 'YYYY-MM-DD'));
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 3, 3, '000003', TO_DATE('2019-01-14', 'YYYY-MM-DD'), TO_DATE('2019-06-26', 'YYYY-MM-DD'));
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 4, 4, '000004', TO_DATE('2019-12-23', 'YYYY-MM-DD'), TO_DATE('2020-07-16', 'YYYY-MM-DD'));
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 5, 5, '000005', TO_DATE('2020-01-13', 'YYYY-MM-DD'), TO_DATE('2020-07-31', 'YYYY-MM-DD'));
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 6, 6, '000006', TO_DATE('2020-02-04', 'YYYY-MM-DD'), TO_DATE('2020-07-23', 'YYYY-MM-DD'));
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 7, 7, '000001', TO_DATE('2020-05-29', 'YYYY-MM-DD'), TO_DATE('2020-11-04', 'YYYY-MM-DD'));
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 8, 8, '000002', TO_DATE('2020-06-15', 'YYYY-MM-DD'), TO_DATE('2020-12-03', 'YYYY-MM-DD'));
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 9, 9, '000003', TO_DATE('2020-07-09', 'YYYY-MM-DD'), TO_DATE('2020-12-15', 'YYYY-MM-DD'));
INSERT INTO OP_COURSES(CODE, ROOM_CODE, COURSE_CODE, PRO_ID, START_DATE, END_DATE)
VALUES(SEQ_OP_COURSES_CODE.NEXTVAL, 10, 10, '000004', TO_DATE('2020-08-03', 'YYYY-MM-DD'), TO_DATE('2021-01-12', 'YYYY-MM-DD'));


--○ 교수자 강의 가능 과목 데이터 입력
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 1);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 2);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 3);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 4);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 5);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 6);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 7);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 8);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 9);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 10);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 11);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 12);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 13);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000001', 14);

INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000002', 1);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000002', 2);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000002', 3);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000002', 4);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000002', 5);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000002', 6);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000002', 7);

INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000003', 8);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000003', 9);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000003', 10);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000003', 11);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000003', 12);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000003', 13);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000003', 14);

INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 1);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 2);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 3);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 4);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 5);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 6);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 7);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 8);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 9);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 10);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 11);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 12);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 13);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000004', 14);

INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 1);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 9);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 11);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 12);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 13);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 14);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 3);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 4);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 5);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 6);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000005', 7);

INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 1);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 2);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 4);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 5);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 7);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 8);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 10);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 11);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 13);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 14);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 3);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 6);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 9);
INSERT INTO PROFESSOR_TEACHABLE_SUBJECTS(CODE, PRO_ID, SUB_CODE)
VALUES(SEQ_PTS_CODE.NEXTVAL, '000006', 12);

------------------- 3차 더미데이터 입력 ---------------------------------------------------------------------------------------

--○ 개설과목(OP_SUBJECTS) 데이터 입력 
-- 1번 개설 과정에 과목 개설 
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 1, 1, 1, TO_DATE('2018-04-16', 'YYYY-MM-DD'), TO_DATE('2018-05-01', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 2, 2, 1, TO_DATE('2018-05-02', 'YYYY-MM-DD'), TO_DATE('2018-05-15', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 3, 3, 1, TO_DATE('2018-05-16', 'YYYY-MM-DD'), TO_DATE('2018-06-20', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 4, 4, 1, TO_DATE('2018-06-21', 'YYYY-MM-DD'), TO_DATE('2018-07-15', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 5, 5, 1, TO_DATE('2018-07-16', 'YYYY-MM-DD'), TO_DATE('2018-10-15', 'YYYY-MM-DD'), 10, 40, 50) ;

--○ 2번과정 개설과목 입력
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 2, 15, 2, TO_DATE('2018-07-23', 'YYYY-MM-DD'), TO_DATE('2018-08-02', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 3, 16, 2, TO_DATE('2018-08-03', 'YYYY-MM-DD'), TO_DATE('2018-08-15', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 4, 17, 2, TO_DATE('2018-08-16', 'YYYY-MM-DD'), TO_DATE('2018-09-12', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 5, 18, 2, TO_DATE('2018-09-12', 'YYYY-MM-DD'), TO_DATE('2018-10-25', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 6, 19, 2, TO_DATE('2018-10-25', 'YYYY-MM-DD'), TO_DATE('2019-01-11', 'YYYY-MM-DD'), 10, 40, 50) ;

--3번 개설과정에 과목 개설
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL , 1, 22, 3, TO_DATE('2019-01-14', 'YYYY-MM-DD'), TO_DATE('2019-02-14', 'YYYY-MM-DD'), 10, 40, 50);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL , 2, 23, 3, TO_DATE('2019-02-15', 'YYYY-MM-DD'), TO_DATE('2019-03-15', 'YYYY-MM-DD'), 20, 40, 40);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL , 3, 24, 3, TO_DATE('2019-03-16', 'YYYY-MM-DD'), TO_DATE('2019-04-17', 'YYYY-MM-DD'), 20, 40, 40);

-- 4번 개설 과정에 과목 개설 
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL , 4, 29, 4, TO_DATE('2019-12-13', 'YYYY-MM-DD'), TO_DATE('2020-01-14', 'YYYY-MM-DD'), 10, 20, 70);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL , 5, 30, 4, TO_DATE('2020-01-14', 'YYYY-MM-DD'), TO_DATE('2020-03-15', 'YYYY-MM-DD'), 10, 20, 70);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 6, 31, 4, TO_DATE('2020-03-16', 'YYYY-MM-DD'), TO_DATE('2020-04-17', 'YYYY-MM-DD'), 20, 40, 40);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 7, 32, 4, TO_DATE('2020-04-17', 'YYYY-MM-DD'), TO_DATE('2020-05-18', 'YYYY-MM-DD'), 20, 40, 40);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 8, 33, 4, TO_DATE('2020-05-18', 'YYYY-MM-DD'), TO_DATE('2020-07-16', 'YYYY-MM-DD'), 10, 45, 45);

-- 5번 개설과정엔 '000005' 교수가 가르치는 과목만 넣을 수 있음(SUB_CODE : 1,3,4 과목을 넣을거다) - 자바이론, 오라클 이론, 오라클 실습

INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 1, 43, 5 ,TO_DATE('2020-01-13', 'YYYY-MM-DD'), TO_DATE('2020-01-31', 'YYYY-MM-DD'), 10, 45, 45) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 1, 49, 5 ,TO_DATE('2020-02-01', 'YYYY-MM-DD'), TO_DATE('2020-02-20', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL , 1, 50, 5 ,TO_DATE('2020-02-21', 'YYYY-MM-DD'), TO_DATE('2020-07-31', 'YYYY-MM-DD'), 15, 35, 50) ;

--6번 개설과정엔 '000006' 교수가 가르치는 과목만 넣을 수 있음(SUB_CODE : 10,11,12,13 과목을 넣을거다) - 파이썬 실습, 빅데이터 이론, 빅데이터 실습, 앱개발이론
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL , 9, 60, 6, TO_DATE('2020-02-04', 'YYYY-MM-DD'), TO_DATE('2020-02-28', 'YYYY-MM-DD'), 15, 35, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL , 9, 61, 6, TO_DATE('2020-03-01', 'YYYY-MM-DD'), TO_DATE('2020-04-15', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL , 9, 67, 6, TO_DATE('2020-04-16', 'YYYY-MM-DD'), TO_DATE('2020-05-20', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL , 10, 62, 6, TO_DATE('2020-05-21', 'YYYY-MM-DD'), TO_DATE('2020-07-23', 'YYYY-MM-DD'), 10, 40, 50) ;

-- 7번 과정에 과목 개설 
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 1, 1, 7, TO_DATE('2020-05-29', 'YYYY-MM-DD'), TO_DATE('2020-06-20', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 2, 3, 7, TO_DATE('2020-06-21', 'YYYY-MM-DD'), TO_DATE('2020-07-10', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 10, 5, 7, TO_DATE('2020-07-11', 'YYYY-MM-DD'), TO_DATE('2020-08-06', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 3, 7, 7, TO_DATE('2020-08-07', 'YYYY-MM-DD'), TO_DATE('2020-08-31', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 9, 9, 7, TO_DATE('2020-09-01', 'YYYY-MM-DD'), TO_DATE('2020-09-30', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 9, 11, 7, TO_DATE('2020-10-01', 'YYYY-MM-DD'), TO_DATE('2020-10-15', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 6, 13, 7, TO_DATE('2020-10-16', 'YYYY-MM-DD'), TO_DATE('2020-11-04', 'YYYY-MM-DD'), 10, 40, 50) ;

-- 8번 과정을 개설하기 위해 과목을 개설해준다

INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 1, 1, '000002', TO_DATE('2020-06-15', 'YYYY-MM-DD'), TO_DATE('2020-06-30', 'YYYY-MM-DD'), 10, 40, 50);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 1, 2, '000002', TO_DATE('2020-07-01', 'YYYY-MM-DD'), TO_DATE('2020-07-31', 'YYYY-MM-DD'), 10, 40, 50);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 2, 3, '000002', TO_DATE('2020-08-01', 'YYYY-MM-DD'), TO_DATE('2020-08-15', 'YYYY-MM-DD'), 10, 40, 50);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 2, 4, '000002', TO_DATE('2020-08-16', 'YYYY-MM-DD'), TO_DATE('2020-09-15', 'YYYY-MM-DD'), 10, 40, 50);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 10, 5, '000002', TO_DATE('2020-09-16', 'YYYY-MM-DD'), TO_DATE('2020-10-15', 'YYYY-MM-DD'), 10, 40, 50);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 10, 6, '000002', TO_DATE('2020-10-16', 'YYYY-MM-DD'), TO_DATE('2020-12-03', 'YYYY-MM-DD'), 10, 40, 50);


-- 9번 개설과정에 과목 개설 
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 3, 22, 9, TO_DATE('2020-07-09', 'YYYY-MM-DD'), TO_DATE('2020-08-01', 'YYYY-MM-DD'), 10, 40, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 9, 23, 9, TO_DATE('2020-08-02', 'YYYY-MM-DD'), TO_DATE('2020-08-30', 'YYYY-MM-DD'), 20, 30, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 9, 24, 9, TO_DATE('2020-08-31', 'YYYY-MM-DD'), TO_DATE('2020-09-25', 'YYYY-MM-DD'), 20, 30, 50) ;
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES (SEQ_OP_SUBJECTS_CODE.NEXTVAL, 7, 28, 9, TO_DATE('2020-09-26', 'YYYY-MM-DD'), TO_DATE('2020-12-10', 'YYYY-MM-DD'), 20, 25, 55) ;

-- 10번 과정 개설과목 입력
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 3, 38, 10, TO_DATE('2020-08-03', 'YYYY-MM-DD'), TO_DATE('2020-09-04', 'YYYY-MM-DD'), 10, 20, 70);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 4, 39, 10, TO_DATE('2020-09-05', 'YYYY-MM-DD'), TO_DATE('2020-10-05', 'YYYY-MM-DD'), 10, 20, 70);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 5, 40, 10, TO_DATE('2020-10-06', 'YYYY-MM-DD'), TO_DATE('2020-11-07', 'YYYY-MM-DD'), 20, 40, 40);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 6, 41, 10, TO_DATE('2020-11-08', 'YYYY-MM-DD'), TO_DATE('2020-12-08', 'YYYY-MM-DD'), 20, 40, 40);
INSERT INTO OP_SUBJECTS (NUM, BOOK_NUM, PTS_CODE, OP_COURSE_CODE, START_DATE, END_DATE, PRE_RATE, PRAC_RATE, WRITE_RATE)
VALUES(SEQ_OP_SUBJECTS_CODE.NEXTVAL, 7, 42, 10, TO_DATE('2020-12-08', 'YYYY-MM-DD'), TO_DATE('2021-01-12', 'YYYY-MM-DD'), 10, 45, 45);


--○ 학생별 과정 수강목록(STUDENTS_COURSES_LIST) 데이터 입력 
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000001', 1);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000002', 1);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000003', 1);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000004', 1);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000005', 2);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000006', 2);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000008', 2);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000009', 2);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000010', 3);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000011', 3);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000012', 3);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000013', 3);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000002', 4);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000015', 4);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000016', 4);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000008', 5);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000017', 5);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000018', 5);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000020', 5);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000008', 6);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000010', 6);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000009', 6);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000012', 7);
INSERT INTO STUDENT_COURSES_LISTS(NUM, STUDENT_ID, OP_COURSE_CODE) VALUES(SEQ_SCL_NUM.NEXTVAL, '000001', 8);

------------------- 4차 더미데이터 입력 ---------------------------------------------------------------------------------------

--○ 성적(SCORES) 데이터 입력
-- 1번 과정(18/04/16 ~ 18/10/15)

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 1, 1, 100, 90, 90);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 2, 1, 100, 80, 90);  -- 중도탈락: 18/05/20
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 3, 1, 100, 60, 90);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 4, 1, 60, 90, 50);

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 1, 2, 100, 70, 80);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 2, 2, 80, 70, 80);  -- 중도탈락: 18/05/20
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 3, 2, 100, 80, 80);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 4, 2, 70, 80, 90);

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 1, 3, 100, 90, 90);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 2, 3, 60, 80, 20);  -- 중도탈락: 18/05/20
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 3, 3, 90, 100, 80);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 4, 3, 80, 100, 100);

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 1, 4, 100, 50, 70);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 2, 4, 40, 20, 30);  -- 중도탈락: 18/05/20
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 3, 4, 70, 70, 80);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 4, 4, 100, 100, 100);

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 1, 5, 100, 80, 80);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 3, 5, 50, 60, 40);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 4, 5, 100, 100, 100);


-- 2번 과정(18/07/23 ~ 19/01/11)

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 5, 6, 100, 80, 70);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 6, 6, 90, 90, 95);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 7, 6, 80, 70, 60);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 8, 6, 70, 60, 70);  -- 중도탈락: 18/10/05

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 5, 7, 70, 70, 70);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 6, 7, 80, 90, 40);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 7, 7, 90, 80, 30);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 8, 7, 100, 40, 100);  -- 중도탈락: 18/10/05

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 5, 8, 80, 60, 50);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 6, 8, 90, 70, 60);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 7, 8, 100, 30, 70);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 8, 8, 70, 60, 90);  -- 중도탈락: 18/10/05

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 5, 9, 90, 30, 70);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 6, 9, 50, 70, 60);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 7, 9, 100, 90, 100);

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 5, 10, 80, 70, 30);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 6, 10, 90, 10, 60);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 7, 10, 100, 90, 40);

-- 3번 과정(19/01/14 ~ 19/06/26) 더미데이터

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 9, 11, 50, 80, 45);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 10, 11, 60, 80, 90);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 11, 11, 70, 20, 30); -- 중도탈락: 19/06/03
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 12, 11, 100, 100, 90);

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 9, 12, 80, 50, 90);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 10, 12, 90, 80, 40);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 11, 12, 40, 50, 60); -- 중도탈락: 19/06/03
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 12, 12, 70, 80, 90);

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 9, 13, 80, 50, 40);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 10, 13, 60, 80, 90);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 11, 13, 90, 40, 50); -- 중도탈락: 19/06/03
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 12, 13, 100, 58, 85);


-- 4번 과정(19/12/23 ~ 20/07/16) 더미데이터

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 13, 14, 100, 90, 80);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 14, 14, 80, 70 ,90);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 15, 14, 0, 0, 0); -- 중도탈락: 20/04/01

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 13, 15, 80, 80, 80);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 14, 15, 90, 80, 70);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 15, 15, 0, 0, 0); -- 중도탈락: 20/04/01

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 13, 16, 80, 90, 50);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 14, 16, 40, 30, 50);


-- 5번 과정(20/01/13 ~ 20/07/31)
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 16, 19, 100, 80, 70);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 17, 19, 45, 67, 34 );
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 18, 19, 45, 56, 78);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 19, 19, 34, 56, 95);

INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 16, 20, 23, 56, 65);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 17, 20, 45, 34, 45);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 18, 20, 45, 45, 45);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 19, 20, 23, 45, 56);

-- 6번 과정 (20/02/04 ~ 20/07/23)
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 20, 22, 43, 45, 56); -- 중도탈락: 20/04/11
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 21, 22, 78, 45, 90);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 22, 22, 23, 87, 98);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 21, 23, 90, 98, 99);
INSERT INTO SCORES(NUM, SCL_NUM, OP_SUB_NUM, PRESENCE, PRACTICE, WRITING) VALUES(SEQ_SCORES.NEXTVAL, 22, 23, 98, 87, 89);


--○ 중도탈락여부(NON_PASS) 데이터 입력 
INSERT INTO NON_PASS(NUM, SCL_NUM, NP_DATE) VALUES(SEQ_NON_PASS.NEXTVAL, 2, TO_DATE('2018-05-20', 'YYYY-MM-DD'));
INSERT INTO NON_PASS(NUM, SCL_NUM, NP_DATE) VALUES(SEQ_NON_PASS.NEXTVAL, 8, TO_DATE('2018-10-05', 'YYYY-MM-DD'));
INSERT INTO NON_PASS(NUM, SCL_NUM, NP_DATE) VALUES(SEQ_NON_PASS.NEXTVAL, 11, TO_DATE('2019-06-03', 'YYYY-MM-DD'));
INSERT INTO NON_PASS(NUM, SCL_NUM, NP_DATE) VALUES(SEQ_NON_PASS.NEXTVAL, 15, TO_DATE('2020-04-01', 'YYYY-MM-DD'));
INSERT INTO NON_PASS(NUM, SCL_NUM, NP_DATE) VALUES(SEQ_NON_PASS.NEXTVAL, 20, TO_DATE('2020-04-11', 'YYYY-MM-DD'));

--○ 커밋 
COMMIT;